### ISSUE TITLE
Handling empty response

### ISSUE THREAD

**Issue by soredake** [dsblv/vk-api-calls#5]
Привет, пытаюсь просто вывести ответ, но код не работает и я не могу понять почему, даже при неправильно переданных выдает 'ура'.
[log.zip](https://github.com/dsblv/vk-api-calls/files/487050/log.zip)

Node 5.0.0

**Comment by dsblv** [comment]
Sup @fenque :hand: 

Видимо переданные данные не настолько неправильны для ВК, чтобы кидать ошибку и он просто выдает пустой ответ:

```
{response: []}
```

В промис, ради полноты данных, я передаю весь объект `response` с кучей инфы, поэтому имеет смысл смотреть только в `response.body`:

``` js
vk.performApiCall('users.get', {
    user_ids: 1
})
.then(res => {
    console.log('ура', res.body);
});
```

Если хочется считать пустой ответ ошибкой, можно сделать так:

``` js
vk.performApiCall('users.get', {
    user_ids: 1
})
.then(res => {
    if (res.body.response && res.body.response.length === 0) {
        throw new Error('Empty response');
    }
    return res.body;
})
.then(data => {
    console.log(data); // Сюда придет ответ ВК
})
.catch(err => {
    console.error(err.message); // Сюда ошибки, включая `Empty response`
});
```

**Comment by soredake** [comment]
Спасибо, думаю ещё было бы хорошо это в readme добавить, хотя бы примерный код запроса к апи, если у кого-то возникут вопросы.
